# UPSC GS Subtopics

gs1 = [
    # Historical & Constitutional Background
    "Historical Underpinning & Evolution",
    "Regulating Act (1773) to Independence Act (1947)",
    "Constituent Assembly",
    "Objective Resolution",
    "Enactment & Enforcement of Constitution",

    # Features of the Constitution
    "Features",
    "Written",
    "Flexible & Rigid",
    "Federal & Unitary",
    "Parliamentary Form of Government (Presidential vs. Parliamentary Type of Government)",
    "Amendments",
    "List of Significant Amendments & Their Provisions",
    "Procedure for Amending Constitution",

    # Significant Provisions
    "Significant Provisions",
    "Fundamental Rights",
    "Directive Principles of State Policy",
    "Judicial Review",
    "Universal Adult Franchise",
    "Single Citizenship",
    "Separation of Powers",
    "Basic Structure",
    "The Doctrine",
    "Judgments & Cases",

    # Federal Structure
    "Functions & Responsibilities of the Union and the States",
    "7th Schedule",
    "Legislative Functions",
    "Financial Functions",
    "Administrative & Quasi-Judicial Functions",
    "Issues & Challenges Pertaining to the Federal Structure",
    "Federal Structure in India - Is India truly Federal?",
    "Cooperative & Competitive Federalism",
    "Centre-State Relations",
    "Legislative Relations",
    "Administrative Relations",
    "Financial Relations",
    "Trends in Centre-State Relations",
    "Inter-State Relations",
    "Inter-state Water Disputes",
    "Inter-State Councils",
    "Public Acts, Records and Judicial Proceedings",
    "Inter-State Trade and Commerce",
    "Zonal Councils",
    "Emergency Provisions",
    "Role of Governor",
    "Reports of Various Commissions",
    "2nd ARC, Punchhi, Sarkaria, etc.",

    # Local Governance & Devolution
    "Devolution of Powers & Finances to Local Levels & Challenges Therein",
    "Role of State Government",
    "Role of State Finance Commission",
    "11th & 12th Schedule",
    "Reasons for Ineffective Performance",
    "Panchayat Devolution Index ( NITI Aayog)",
    "Steps That Can Be Taken to Improve Their Performance",

    # Separation of Powers & Checks and Balances
    "Separation of Powers Between Various Organs",
    "Doctrine of Separation of Power",
    "Separation of Power in Indian Constitution",
    "Doctrine of Checks & Balances",
    "Provisions for Checks & Balances in Indian Constitution",
    "Related Judgments - Golaknath case, Kesavananda Bharati, Indira Gandhi Vs Raj Narain, Ram Jawaya vs Punjab",
    "Dispute Redressal Mechanisms and Institutions",
    "RTI",
    "PIL",
    "Tribunals, etc.",

    # Comparison with Other Countries
    "Comparison of the Indian Constitutional Scheme With That of Other Countries Parliament & State Legislatures",
    "Structure, Functioning, Conduct of Business, Powers & Privileges",
    "Written Constitution",
    "Blend of Rigidity and Flexibility",
    "Federal System with Unitary Bias",
    "Parliamentary Form of Government",
    "Synthesis of Parliamentary Sovereignty and Judicial Supremacy",
    "Integrated and Independent Judiciary",
    "Fundamental Rights, Directive Principles of State Policy, Fundamental Duties",
    "Secular State",
    "Universal Adult Franchise",
    "Single Citizenship",
    "Emergency Provisions",
    "Three-tier Government",
    "Due Process of Law vs. Procedure Established by Law",
    "Impeachment of President, etc.",

    # Executive, Legislature, Judiciary
    "Structure, Organization & Functioning of the Executive and the Judiciary",
    "Executive",
    "Union:",
    "President",
    "Prime Minister",
    "Council of Ministers",
    "Cabinet Secretariat",
    "State:",
    "Governor",
    "Chief Minister",
    "Council of Ministers",
    "Secretariat",
    "Judiciary",
    "Three-Tier Structure",
    "Chief Justice of India",
    "SC & HC Judges",
    "Jurisdiction",
    "Ministries and Departments of the Government",
    "Cabinet Ministries",
    "Other Ministries",
    "Parliamentary Secretaries",

    # Pressure Groups & Representation
    "Pressure Groups & Formal/informal Associations & Their Role in Polity",
    "Characteristics of Pressure Groups",
    "Pressure Groups & Political Parties",
    "Pressure Groups & Interest Groups",
    "Types of Pressure Groups",
    "Functions, Role & Importance of Pressure Groups",
    "Techniques/Methods of Pressure Groups",
    "Pressure Groups in India",
    "Shortcomings of Pressure Groups",
    "Salient Features of Representation of People's Act",

    # Constitutional & Statutory Bodies
    "Appointment to Various Constitutional Posts",
    "Appointment, Powers, Functions & Responsibilities of:",
    "Election Commission",
    "Union Public Service Commission",
    "State Public Service Commission",
    "Finance Commission",
    "National Commission for SCs",
    "National Commission for STs",
    "Special Officer for Linguistic Minorities",
    "Comptroller and Auditor General of India",
    "Attorney General of India",
    "Advocate General of the State",

    # Regulatory & Quasi-Judicial Bodies
    "Statutory, Regulatory & Quasi-Judicial Bodies",
    "NITI Aayog",
    "RBI",
    "National Human Rights Commission",
    "State Human Rights Commission",
    "Central Information Commission",
    "Central Vigilance Commission",
    "Central Bureau of Investigation",
    "Lokpal and Lokayuktas",
    "National Commission for Women",
    "National Commission for Backward Classes",
    "National Commission for Minorities",
    "Insurance Regulatory and Development Authority",
    "Securities and Exchange Board of India",
    "Competition Commission of India",
    "Telecom Regulatory Authority of India",
    "Central Electricity Regulatory Commission",
    "Atomic Energy Regulatory Board",
    "Central Pollution Control Board",
    "Medical Council of India",
    "Inland Waterways Authority of India",
    "Central Ground Water Authority",
    "Directorate General of Civil Aviation",
    "Pension Fund Regulatory and Development Authority",
    "Food Safety and Standards Authority of India",
    "Bar Council of India",
    "University Grants Commission",
    "Financial Stability and Development Council",
    "All India Council for Technical Education",
    "National Green Tribunal",
    "Competition Appellate Tribunal",
    "Income-Tax Appellate Tribunal",
    "Cyber Appellate Tribunal",
    "Intellectual Property Appellate Board",

    # Governance & Policies
    "Governance",
    "Government Policies & Interventions for Development",
    "Government Policies & Interventions in Various Sectors",
    "Health, Gender, Education, Poverty, Economic etc",
    "Issues Arising Out of Their Design & Implementation",
    "Concerns/Issues",
    "Suggestions for Improvement",
    "Critical Assessment of Centrally Sponsored Schemes (CSS)",
    "Rationalisation of CSS",
    "Analysis of Main Schemes:",
    "Beti Bachao Beti Padhao",
    "Smart City",
    "Swachh Bharat Abhiyan",
    "MGNERGA",
    "Digital India",
    "Make in India",
    "Skill India",
    "PM Jan Dhan Yojana",
    "Start-up India etc.",

    # Development Processes & NGOs
    "Development Processes & the Development Industry",
    "Role of Social Capital Organisations",
    "Indian Context",
    "Classification",
    "Provisions for the Third Sector in the Indian Constitution",
    "National Policy on the Voluntary Sector 2007",
    "Non-Governmental Organisations",
    "Role and Impact of Non-governmental Organizations",
    "Issue Areas: Accreditation, Legitimacy & Accountability, Foreign Funding etc.",
    "Self Help Groups (SHGs)",
    "Need for SHGs",
    "Benefits of SHGs",
    "Weaknesses of SHGs",
    "Challenges",
    "Measures to Make SHGs Effective",
    "Case Studies: Kudumbashree (Kerala), Mahila Arthik Vikas Mahamandal (Maharashtra)",
    "Societies, Trusts and Cooperatives",
    "Societies",
    "Trust",
    "Religious Endowments",
    "Cooperatives –",
    "Need for Cooperatives",
    "Constitutional Provisions",
    "National Policy on Co-operatives, 2002",
    "Issues and Challenges in the Cooperatives Sector",

    # Governance, Transparency & Accountability
    "Important Aspects of Governance, Transparency & Accountability",
    "Governance",
    "Dimensions of Governance",
    "Good Governance (GG)",
    "Aspects of GG",
    "Barriers to GG",
    "Necessary Pre-conditions for GG",
    "How to Ensure GG",
    "E-Governance",
    "Applications",
    "Models",
    "Successes",
    "Limitations",
    "Potential",
    "Recent e-governance Initiatives by Government",
    "Citizens Charters (CC)",
    "Components of CC",
    "Features of CC",
    "Six Principles of CC",
    "Shortcomings of CC",
    "Measures to Make CC Effective",
    "Sevottam Model",
    "Aspects of Transparency",
    "Elements & Types of Accountability",
    "Means to ensure Transparency & Accountability",
    "RTI",
    "Social Audit",
    "Whistleblower Protection Bill",
    "Lokpal & Lokayuktas Act",

    # Civil Services
    "Role of Civil Services in a Democracy",
    "Relationship Between Civil Service And Democracy",
    "Role Played By Civil Services",
    "Advisory Role in Policy Making",
    "Institutionalise Socio-economic change",
    "Discharge Delegated Functions",
    "Administer Law of the Land",
    "Watchdogs",
    "Continuity in times of Political Instability",
    "Record-Keeping",
    "Channel of Communication",
    "Ailments/Issues Afflicting Indian Civil Services",
    "Lack of Professionalism & Poor Capacity Building",
    "Inefficient Incentive Systems",
    "Outdated Rules & Procedures",
    "Systemic Inconsistencies in Promotion",
    "Lack of Adequate Transparency & Accountability Procedures",
    "Arbitrary & Whimsical Transfers",
    "Political Interference & Administrative Acquiescence",
    "Gradual Erosion in Values & Ethics",
    "Redtapism",
    "Elitist in Nature",
    "Poor Pay",
    "Tendency to Capture Power",
    "Reforming Bureaucracy to Strengthen Democracy",
    "Setting Right the Asymmetry of Power",
    "Insulating Civil Servants from Undue Political Interference",
    "Professionalisation with Stability of Tenure & Competition",
    "Citizen-Centric Administration",
    "Accountability",
    "Outcome Orientation",
    "Promoting Public Service Values & Ethics",

    # Social Justice
    "SOCIAL JUSTICE",
    "Welfare Schemes for Vulnerable Sections",
    "Schemes for the Following Vulnerable Sections",
    "SCs & STs",
    "Minorities",
    "Children",
    "Elderly",
    "Disabled",
    "Women",
    "Transgender",
    "Performance of These Schemes",
    "Mechanisms, Laws, Institutions & Bodies Constituted for Protection & Betterment of These Vulnerable Sections",
    "SCs:",
    "The Protection of Civil Rights Act",
    "The Scheduled Castes and the Scheduled Tribes (Prevention of Atrocities) Act",
    "National Commission for Scheduled Castes",
    "Scheduled Castes Sub Plan",
    "Disabled:",
    "The Rehabilitation Council of India Act",
    "The Persons with Disabilities (Equal Opportunities, Protection of Rights and Full Participation) Act",
    "Mental Retardation and Multiple Disabilities Act",
    "The National Trust for Welfare of Persons with",
    "Autism, Cerebral Palsy, Mental Retardation and Multiple Disabilities Act",
    "Rights of the Persons with Disabilities Act",
    "STs:",
    "National Commission for Scheduled Tribes",
    "Tribal Sub Plan",
    "TRIFED",
    "Scheduled Tribes and Other Traditional Forest Dwellers (Recognition of Forest Rights) Act",
    "Minorities:",
    "National Commission for Minorities",
    "National Commission for Religious and Linguistic Minorities",
    "Women & Children",
    "The Immoral Traffic (Prevention) Act",
    "The Indecent Representation of Women (Prevention) Act",
    "The Dowry Prohibition Act",
    "The Commission of Sati (Prevention) Act",
    "The Prohibition of Child Marriage Act",
    "Protection of Women from Domestic Violence Act",
    "Juvenile Justice (Care and Protection of Children) Act",
    "Central Adoption Resource Agency (CARA)",
    "The Protection of Children from Sexual Offences (POCSO) Act",
    "Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal)",
    "Pre-Conception and Pre Natal Diagnostic Techniques (PC&PNDT) Act",
    "Gender Budgeting",
    "National Policy for Women",
    "Domestic Violence Act",
    "Maternity Benefit (Amendment) Act",
    "Elderly",
    "Maintenance and Welfare of Parents and Senior Citizens Act",

    # Social Sector/Services
    "Issues Relating to Development & Management of Social Sector/Services",
    "Health",
    "India’s Performance on Various Health Indicators",
    "Weaknesses of Indian Healthcare System",
    "Health Infrastructure in India",
    "Universal Health Coverage",
    "12th FYP Strategy",
    "Universal Health Coverage",
    "Health Insurance",
    "National Family Health Survey",
    "National Health Policy",
    "National Health Mission",
    "Maternal & Adolescent Health",
    "Child Health",
    "Antimicrobial Resistance",
    "Disease Burden in India",
    "Measures to Ensure Good Health Outcomes",
    "Government Initiatives",
    "Education",
    "Status of Literacy in India",
    "Education Structure in India",
    "Challenges Faced by Education Sector in India",
    "Reforms Required",
    "Government Initiatives",
    "ASER Report",
    "Financing Education",
    "Subramanian Panel Report",
    "Human Resource",
    "Need For Skill Development",
    "Skill Development Initiatives",
    "Challenges in Skilling Landscape in India",
    "Shortcomings of Current Skill Development Initiatives",
    "Reforms Required",
    "Steps that can Be Taken",
    "Issues Relating to Poverty & Hunger",
    "Relation between Poverty & Hunger",
    "Distribution of Poverty & Hunger",
    "Magnitude & Trends of Poverty & Hunger",
    "Causes of Poverty & Hunger",
    "Cost/Impact of Poverty & Malnutrition",
    "MDGs & SDGs",
    "Food and nutrition insecurity - a consequence of structural inequities",
    "Constraints in Reducing Poverty & Hunger",
    "Measure to Reduce Poverty & Hunger – National Food Security Act, Mid-day Meal Scheme, MGNREGA etc.",

    # International Relations
    "INTERNATIONAL RELATIONS",
    "India and its Neighborhood – Relations",
    "India and its Neighborhood – Relations: India’s Relations With",
    "India and its Neighborhood – Relations: China",
    "India and its Neighborhood – Relations: Pakistan",
    "India and its Neighborhood – Relations: Myanmar",
    "India and its Neighborhood – Relations: Bhutan",
    "India and its Neighborhood – Relations: Bangladesh",
    "India and its Neighborhood – Relations: Sri Lanka",
    "India and its Neighborhood – Relations: Afghanistan",
    "India and its Neighborhood – Relations: Nepal",
    "India and its Neighborhood – Relations: Maldives",
    "Bilateral, Regional & Global Groupings & Agreements Involving India and/or Affecting India's Interests: India’s Major Foreign Policy Doctrines Since 1947",
    "Bilateral, Regional & Global Groupings & Agreements Involving India and/or Affecting India's Interests: Non-aligned Movement (NAM)",
    "Bilateral, Regional & Global Groupings & Agreements Involving India and/or Affecting India's Interests: Nuclear Doctrine",
    "Bilateral, Regional & Global Groupings & Agreements Involving India and/or Affecting India's Interests: Gujral Doctrine",
    "Bilateral, Regional & Global Groupings & Agreements Involving India and/or Affecting India's Interests: Look East to Act East",
    "Bilateral, Regional & Global Groupings & Agreements Involving India and/or Affecting India's Interests: Think West, etc.",
    "Bilateral Relations With",
    "Bilateral Relations With: Major Powers Like – USA, Russia, Japan",
    "Bilateral Relations With: Central Asian Countries",
    "Bilateral Relations With: West Asian Countries",
    "Bilateral Relations With: African Countries",
    "Bilateral Relations With: Australia & New Zealand",
    "Bilateral Relations With: EU & European Countries",
    "Bilateral Relations With: Latin American Countries",
    "Bilateral Relations With: Pacific Countries",
    "Regional & Global Groupings",
    "Regional & Global Groupings: SAARC",
    "Regional & Global Groupings: BRICS",
    "Regional & Global Groupings: BBIN & BCIM",
    "Regional & Global Groupings: BIMSTEC",
    "Regional & Global Groupings: IBSA",
    "Regional & Global Groupings: ASEAN & RCEP",
    "Regional & Global Groupings: India-Africa Forum",
    "Regional & Global Groupings: SCO",
    "Regional & Global Groupings: Ashgabat Agreement",
    "Regional & Global Groupings: FIPIC",
    "Regional & Global Groupings: IOR-ARC",
    "Regional & Global Groupings: Mekong Ganga Cooperation (MGC)",
    "Regional & Global Groupings: Raisina Dialogue",
    "Regional & Global Groupings: Heart of Asia Conference",
    "Regional & Global Groupings: East Asia Summit",
    "Regional & Global Groupings: G-20",
    "Regional & Global Groupings: Asian Development Bank",
    "National Security Summit",
    "Multilateral Nuclear Export Regulatory Regimes: Wassenar, MTCR, Australia Group",
    "Asian Development Bank",
    "APEC, etc",
    "Effect of Policies & Politics of Developed & Developing Countries on India's Interests",
    "One Belt One Road",
    "International North–South Transport Corridor",
    "Global Trade War",
    "Global Currency War",
    "Syrian Crisis",
    "UN Reforms",
    "WTO Reforms",
    "South China Sea Conflict",
    "Brexit",
    "Deglobalisation & Protectionism – US Sanctions on Iran, US Pullout from Paris Agreement, H-1B Visa Issue etc.",
    "OPEC Oil Prices Manipulation, etc.",
    "Indian Diaspora",
    "Spread of Indian Diaspora",
    "India’s Diaspora Policy & Engagement Initiatives",
    "OCI",
    "Pravasi Bharatiya Divas",
    "Know India Programme, etc.",
    "LM Singhvi High Level Committee on the Diaspora",
    "Role played by Indian Diaspora",
    "Issues Concerning the Diaspora:",
    "Dual Nationality",
    "Remittances, etc.",
    "Important International Institutions",
    "UN & its Agencies",
    "WTO",
    "World Bank",
    "IMF",
    "World Economic Forum",
    "Commonwealth of Nations, etc.",
]
