gs4 = [
    "Ethics and Human Interface",
    "Attitude: Content, Structure, Function",
    "Moral and Political Attitudes",
    "Social Influence and Persuasion",
    "Aptitude and Foundational Values for Civil Service",
    "Integrity",
    "Impartiality and Non-partisanship",
    "Objectivity",
    "Dedication to Public Service",
    "Empathy, Tolerance and Compassion",
    "Emotional Intelligence",
    "Contributions of Moral Thinkers and Philosophers",
    "Public/Civil Service Values and Ethics in Public Administration",
    "Status and Problems of Ethical Dilemmas in Government",
    "Laws, Rules, Regulations and Conscience as Sources of Ethical Guidance",
    "Accountability and Ethical Governance",
    "Strengthening of Ethical and Moral Values in Governance",
    "Ethical Issues in International Relations and Funding",
    "Corporate Governance",
    "Probity in Governance",
    "Concept of Public Service",
    "Philosophical Basis of Governance and Probity",
    "Information Sharing and Transparency in Government",
    "Right to Information",
    "Codes of Ethics and Codes of Conduct",
    "Citizen’s Charters",
    "Work Culture",
    "Quality of Service Delivery",
    "Utilization of Public Funds",
    "Challenges of Corruption",
    "Case Studies on Above Issues"
]