name: Send Prelims Pointer to Kindle

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Every day at 5 AM UTC

jobs:
  send-to-kindle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y calibre
        pip install -r requirements.txt

    - name: Run script to send EPUB
      env:
        KINDLE_EMAIL: ${{ secrets.KINDLE_EMAIL }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: 587
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        FROM_EMAIL: "ajaykg6917@gmail.com"
      run: python send_daily_to_kindle.py
